# Generated by Django 3.2.4 on 2021-07-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_tournament_amountusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
