# Generated by Django 3.2.4 on 2022-05-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20210701_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='loser',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='loserResult',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='winnerResult',
            field=models.CharField(default='', max_length=255),
        ),
    ]
