# Generated by Django 3.2.4 on 2021-07-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20210701_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='amountUsers',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
